# Generated by Django 2.2 on 2021-03-05 15:38

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('descriptions', models.TextField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('raiting', models.FloatField(default=0.0)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('sku', models.CharField(max_length=10, unique=True)),
                ('available', models.BooleanField(default=True, verbose_name='Available')),
                ('categories', models.ManyToManyField(to='catalog.Catalog', verbose_name='Category')),
            ],
            options={
                'ordering': ['name', '-price'],
            },
        ),
    ]
