# Generated by Django 3.1.4 on 2021-03-31 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210331_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
