# Generated by Django 3.1.4 on 2021-04-21 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210325_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipment_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
